### ISSUE TITLE
Titulo nuevo de columna en sospechosos: Localidad

### ISSUE THREAD

**Issue by elzr** [covidctdmx/covid_ctd_mx#14]
Desde el lunes 23 de Marzo Secretaria de Salud agrego una columna a los casos sospechosos: localidad.

Los titulos de las columnas del csv parecen estar fijas y eso hace que el csv tenga que ser manualmente corregido a agregarle localidad. 

Github mismo se traba al desplegar el error pero lo identifica correctamente: https://github.com/covidctdmx/covid_ctd_mx/blob/master/originales/20200324_sos_20200324_194142.csv

**Comment by covidctdmx** [comment]
Hola elzr, me dí cuenta de esto pero quice esperar a ver si era algún cambio que sería permanente o un cambio temporal, ya estoy haciendo pruebas para agregar esta nueva columna y espero terminar de adoptar este cambio a la brevedad.

;D covidctdmx

**Comment by covidctdmx** [comment]
Por le momento modificare de manera manual los archivos con problemas para que puedas utilizarlos en lo que termino de implementar el código.

;D covidctdmx

**Comment by elzr** [comment]
Muchas gracias!
