### ISSUE TITLE
Nombre mas cortos o mas claros

### ISSUE THREAD

**Issue by elzr** [covidctdmx/covid_ctd_mx#15]
Los nombres son tan largos que Github no alcanza a desplegarlos en la columna de nombres. El problema es que no se distingue cual es el PDF y cual es el CSV, ni por la columna de nombre ni por la de descripcion.

![image](https://user-images.githubusercontent.com/183877/77577266-138a3680-6e9c-11ea-99ed-b07d3a95df73.png)

**Comment by covidctdmx** [comment]
Hola elzr, la razón para tener un nombre tan largo es para que en momento en el que existan más de un archivo PDF o CSV, esto puede darse si por alguna razón se ponen a disposición dos archivos con la misma fecha.

Por lo anterior me gustaría proponerte este par de opciones para que pudieras disponer de los archivos sin tener que cambiar los nombres:

- - Bajar el archivo completo del branch MASTER, esto se logra accediendo a la url del proyecto (https://github.com/covidctdmx/covid_ctd_mx) y luego dando click al botón "Clone or Download" y luego seleccionar "Download ZIP"
- 
- ![imagen](https://user-images.githubusercontent.com/62459981/77601620-db511b00-6ed0-11ea-81d1-0be84eeaf088.png)
- 
- - Puedes clonar el proyecto completo a tu maquina, haciendo un "git clone", una vez que tengas el proyecto clonado, solo necesitarías hacer un "git pull" para actualizar los archivos contenidos en el proyecto, para esto hay muchas maneras de hacerlo te comparto unos enlaces que pueden ayudarte este proceso.
 
- Instalar la aplicación de github (https://desktop.github.com/)
- Instalar github en el sitema operativo y manejarlo por comandos, solo ocupas estos dos comandos

```
#Comando para clonar el repositorio
git clone https://github.com/covidctdmx/covid_ctd_mx
#Comando para actualizar el contenido que se clonó con la información nueva que se encuentre en el repositorio en línea
git pull
```
Pedes apoyarte en este manual rápid de git (http://rogerdudler.github.io/git-guide/) en los títulos "checkout a repository" y "update & merge", para poder ejecutar los comandos debes instalar git en alguna máquina (https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

Avisame si tienes algún problema para ejecutar algunas de las alternativas anteriores.

;D covidctdmx

**Comment by elzr** [comment]
Gracias por las opciones covidctdmx. Son buenas pero es que los que me reportaron ese problema son amigos no técnicos y es mucha complejidad para ellos. Lo que acabo funcionando es simplemente poner el cursor en el enlace y esperar a que salga el tooltip con el nombre completo donde sale la extensión de archivo 🤷‍♂️. Es una solución muy sencilla pero a fin de cuentas es un problema sencillo. 🙂

**Comment by covidctdmx** [comment]
Hola elzr, acabo de hacer una modiicación para crear una versión de archivos csv de nombres cortos, estos los puedes encontrar en el directorio "csv", también hice una modificación sobre el tamaño de las columnas del archivo de sospechosos.

Espero te ayude, saludos

;D covidctdmx
