### ISSUE TITLE
Que sucede con las fechas de inicio de síntomas (sospechosos) a partir del caso No. 2753

### ISSUE THREAD

**Issue by 0xp4blo** [covidctdmx/covid_ctd_mx#31]
Hola, estoy utilizando el dataset para crear un API publico [(pablotrinidad/mxctd)](https://github.com/pablotrinidad/mxctd) y note que en los registros sospechosos el valor de la fecha en la que comenzaron a presentar síntomas pasa de ser una fecha a ser un número.

**CSV**
![Screen Shot 2020-04-02 at 1 58 06 AM](https://user-images.githubusercontent.com/5308050/78224548-f948ed80-7485-11ea-9bf2-cf79516fc50b.png)

**PDF original**
![Screen Shot 2020-04-02 at 1 58 34 AM](https://user-images.githubusercontent.com/5308050/78224562-006ffb80-7486-11ea-9fa6-e6af8132adcd.png)

Sabes qué sucedió ahí?

PD: Gracias por tu aportación

**Comment by covidctdmx** [comment]
Hola Pablo (@pablotrinidad), es un problema recurrente en los archivos PDF oficiales, seguramente porque es exportado desde Microsoft Excel, este número es una fecha en el formato que utiliza Ms Excel "El sistema de fecha 1900", al final del comentario te dejo un par de enlaces que te pueden ayudar a comprenderlo.

Disculpa porque hasta ahora no he podido ser más claro sobre el contenido del proyecto, pero te explico a continuación:

- los archivos convertidos desde los originales en PDF, se encuentran en el directorio originales, estos archivos están convertidos tal y como aparecen en el original, con la finalidad de dejar un archivo con el contenido intácto del original, también mantienen en el nombre la fecha de descarga de cada archivo, por si en algún momento se publica más de un archivo con el mismo nombre pero diferente contenido, se puedan guardar ambas versiones
- los archivos dentro del directorio csv son los mismos que los originales, solo que con nombre corto para su rápida identificación, fué una petición de un usuario de la información
- los archivos dentro del directorio merge son una versión ampliada de los convertidos iniciales de los originales, estos están más estandarizados en cantidad de columnas, fechas, mayúsculas en la columna estado, además de incluir una columna con una cadena que se forma de unir los datos partículares de cada paciente con la finalidad de identificar a cada uno y en otra columna los últimos 10 carácteres del hash md5 de esta cadena; puedes observar que en estos archivos el problema de las fechas que mencionas ya fué corregido
- existe un archivo dentro del directorio merge llamado supermere.csv que contiene todos los datos que se han publicado hasta ahora en orden cronológico, esto lo hice para poder rastrear el historial de cada paciente

Creo que después de revisar los archivos dentro del merge, podrías ocuparlos en tu proyecto.

Te comparto algunas imagenes del contenido que buscas:
- PDF original
![imagen](https://user-images.githubusercontent.com/62459981/78235003-3668ac00-7495-11ea-9e35-1478c470e0d3.png)
- CSV en directorio originales y con nombre corto en directorio csv
![imagen](https://user-images.githubusercontent.com/62459981/78235094-57c99800-7495-11ea-90d8-c3ca8590ba15.png)
- CSV en directorio merge/pos o merge/sos
![imagen](https://user-images.githubusercontent.com/62459981/78235175-7334a300-7495-11ea-9292-58f316fb7882.png)



Saludos
;D

https://docs.microsoft.com/es-es/office/troubleshoot/excel/1900-and-1904-date-system
https://exceltotal.com/fechas-en-excel/

**Comment by 0xp4blo** [comment]
Muchas gracias @covidctdmx! Usaré `supermerge.csv` 💕

**Comment by covidctdmx** [comment]
@pablotrinidad, me gustaría que supieras que los identificadores (cadena con columnas constantes del paciente y el hash) tiene un problema de ambiguedad con algunos pacientes que coinciden en carácterísticas pero parecen ser dos diferentes personas, para reconocer este comportamiento puedes buscar ID's que aparecen más de una vez en la misma fecha.

Saludos
;D
